# Generated by Django 5.2 on 2025-07-12 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_post_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='profile',
        ),
    ]
